name : Build and deploy package

on: 
  push: 
    branches:
      - main
  
jobs:
  build-and-deploy:
    runs-on: unbutu-latest

    steps: 
      - uses: actions/checkout@main

      - name: Set up .Net Core
        uses: actions/setup-dotner@v1
        with:
          dotnet-version: '5.0.x'
          
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test

      - name: Create the Package
        run: dotnet pack --configuration Release

      - name: Publish
        run: dotnet nuget push "Gravatar/bin/Release/GravatarMagno.1.0.0.nupkg" -K ${{secrets.NUGET_TOKEN}} -s https://api.nuget.org/v3/index.json